service: web-1337-attac-us
image: jackwillis/1337.attac.us

servers:
  - 1337.attac.us

proxy:
  ssl: true
  host: 1337.attac.us

ssh:
  user: ubuntu

builder:
  arch: amd64

registry:
  server: ghcr.io
  username: KAMAL_REGISTRY_USER
  password:
    - KAMAL_REGISTRY_PASSWORD
