service: 1337-attac-us
image: red-panda-industries/1337.attac.us

servers:
  - 1337.attac.us

proxy:
  ssl: true
  host: 1337.attac.us

ssh:
  user: george

builder:
  arch: amd64

registry:
  server: ghcr.io
  username: jackwillis
  password: <%= ENV['KAMAL_REGISTRY_PASSWORD'] %>
